### ISSUE TITLE
freebase_contriever_index目录下缺少了index文件，导致代码无法运行

### ISSUE THREAD

**Issue by 233function** [ltl3A87/KB-BINDER#1]

**Comment by Maydaytyh** [comment]
请问你解决这个问题了吗？能否通过其他方式生成？

**Comment by ltl3A87** [comment]
hi, you can download the index file here:  https://drive.google.com/file/d/1hnyW-_k0YaAUZDTdYzhbKDTnFuLEW-W2/view?usp=sharing
