### ISSUE TITLE
Could you provide the complete code?

### ISSUE THREAD

**Issue by JiaangL** [ltl3A87/KB-BINDER#3]
Hi there! I'm trying to run the code, but it seems like some code hasn't been uploaded yet. 
For example, the folder `utils/` is missing. And I don't know where to replace the virtuoso service url (README says `utils/sparql_executer.py`). 
Could you provide the complete code which is needed to run the experiments? Thank you very much!

**Comment by ltl3A87** [comment]
Hi, sorry for the misleading, you can replace the url in sparql_executer.py not utils/sparql_executer.py.

**Comment by JiaangL** [comment]
Thanks for your quick reply. I have another question about GrailQA. I'm not familiar with this dataset. I want to ask when will the test data be used, i.e., `data/GrailQA/grailqa_v1.0_test_public.json`.? I haven't seen this file used in the code. What's the use of this file?

Thanks!

**Comment by ltl3A87** [comment]
You can refer to the homepage of GrailQA: https://dki-lab.github.io/GrailQA/ to see the setting for evaluation of test set of GrailQA. Basically, you need to submit your results to their official website to get the score for test set. And you can only tune your model on dev set.

**Comment by JiaangL** [comment]
Thanks a lot for the reply and reference. Besides GrailQA, could you provide the script for running on other datasets mentioned in the paper (e.g., WebQSP, GraphQA, and MetaQA)? Moreover, could you provide the implementation of the model which uses retrieved exemplars? 
I would greatly appreciate it if you could release these codes, because they will help my study and research.

**Comment by mk2x15** [comment]
Hi, same question here >> could you provide the script for running on other datasets mentioned in the paper (e.g., WebQSP, GraphQA, and MetaQA)?

**Comment by ltl3A87** [comment]
Hi, I just uploaded the datasets of webqsp, graphqa and metaqa (data+implementation) in the same gdrive link, you can download and play with them. I also updated the code for retrieval-augmented KB-BINDER. Hope it helps.
