### ISSUE TITLE
Some confusion code in few_shot_kbqa.py

### ISSUE THREAD

**Issue by cdhx** [ltl3A87/KB-BINDER#4]
Hi, thanks for publishing the code of this work!

I am confused about some codes in the few_shot_kbqa.py, they seem clerical errors.

In line 37, https://github.com/ltl3A87/KB-BINDER/blob/main/few_shot_kbqa.py#L37

```
 if any([x in data["question"] for x in compare_list]):
```

```data["question"]``` seems should be ```data['s_expression']```

In line 423, https://github.com/ltl3A87/KB-BINDER/blob/main/few_shot_kbqa.py#L423
 

```
if gene_type == "Comparison;":
```

The ;  seems not expected to appear.

Besides, line 556 to 567 seems to construct a useless list (i.e. rela_drops_all), it has not been used in other places.

Looking forward to your reply!

**Comment by ltl3A87** [comment]
Hi, thanks for pointing out these issues, and sorry for the confusion due to the typos and redundant code I produced during re-factor the code. I have updated a rectified version.
